### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to McInfected v1.4.4

### ISSUE THREAD

**Issue by PhanaticD** [Bimmr/BimmCore#4]
```
[20:12:03 ERROR]: Could not pass event EntityDamageByEntityEvent to McInfected v1.4.4
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.2.jar:git-Paper-1032]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:91) [patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:576) [patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:481) [patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:608) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity0(EntityLiving.java:1329) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity0(EntityHuman.java:871) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:871) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity(EntityHuman.java:789) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityPlayer.damageEntity(EntityPlayer.java:528) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityHuman.attack(EntityHuman.java:1030) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityPlayer.attack(EntityPlayer.java:1203) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1608) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.2.jar:git-Paper-1032]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:821) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.2.jar:git-Paper-1032]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at me.bimmr.bimmcore.scoreboard.BoardLine.build(BoardLine.java:167) ~[?:?]
        at me.bimmr.bimmcore.scoreboard.BoardLine.setText(BoardLine.java:112) ~[?:?]
        at com.bimmr.mcinfected.Lobbys.IScoreboard.update(IScoreboard.java:214) ~[?:?]
        at com.bimmr.mcinfected.Lobbys.IScoreboard.update(IScoreboard.java:341) ~[?:?]
        at com.bimmr.mcinfected.Lobbys.IScoreboard.update(IScoreboard.java:312) ~[?:?]
        at com.bimmr.mcinfected.IPlayers.IPlayer.infect(IPlayer.java:568) ~[?:?]
        at com.bimmr.mcinfected.IPlayers.IPlayer.die(IPlayer.java:143) ~[?:?]
        at com.bimmr.mcinfected.Listeners.EntityDamageByEntity.onPlayerDamage(EntityDamageByEntity.java:174) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor401.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1032]
        ... 27 more
```

**Comment by PhanaticD** [comment]
another similar issue

```
[20:44:46 ERROR]: Could not pass event EntityDamageByBlockEvent to McInfected v1.4.4
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.2.jar:git-Paper-1032]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:91) [patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:483) [patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:608) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity0(EntityLiving.java:1329) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity0(EntityHuman.java:871) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:871) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity(EntityHuman.java:789) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityPlayer.damageEntity(EntityPlayer.java:528) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityLiving.Y(EntityLiving.java:1426) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.Entity.kill(Entity.java:498) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.Entity.checkAndDoHeightDamage(Entity.java:437) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.Entity.U(Entity.java:419) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityLiving.U(EntityLiving.java:197) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.Entity.A_(Entity.java:329) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1843) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityHuman.A_(EntityHuman.java:143) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityPlayer.playerTick(EntityPlayer.java:286) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.PlayerConnection.F_(PlayerConnection.java:139) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:239) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:150) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:916) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.2.jar:git-Paper-1032]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at com.bimmr.mcinfected.IPlayers.IPlayer.equip(IPlayer.java:165) ~[?:?]
        at com.bimmr.mcinfected.IPlayers.IPlayer.respawn(IPlayer.java:834) ~[?:?]
        at com.bimmr.mcinfected.IPlayers.IPlayer.die(IPlayer.java:145) ~[?:?]
        at com.bimmr.mcinfected.Listeners.EntityDamage.onEntityDamage(EntityDamage.java:83) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor402.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1032]
        ... 29 more
```

**Comment by Bimmr** [comment]
This is not a BimmCore issue.
